### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by sbimochan** [sbimochan/zoom-mirror#14]
Create a design in figma or similar tools.
Logo should be simple and meaningfull.
It needs to be added on Readme as well of bigger size.

**Comment by ywalia01** [comment]
I'd like to work on this. Could you provide some more details?

**Comment by sbimochan** [comment]
> I'd like to work on this. Could you provide some more details?
kindly check above description.

**Comment by ywalia01** [comment]
Okay @sbimochan

**Comment by chiaramistro** [comment]
Hello. May I also work on this?

**Comment by sbimochan** [comment]
> Hello. May I also work on this?

ofcourse. shoot your best

**Comment by chiaramistro** [comment]
I created the logo. How can I add it to readme? (uploads are not allowed)

**Comment by isNan909** [comment]
I would like to also contribute on this issue @sbimochan. Can you please assign this to me.

**Comment by isNan909** [comment]
Please refer my pull request **#18**

**Comment by sbimochan** [comment]
fixed
