### ISSUE TITLE
Display loading spinner with text below description when streaming is false.

### ISSUE THREAD

**Issue by sbimochan** [sbimochan/zoom-mirror#2]
- Text something like: 
You need to allow webcam access first. We assure you that we don't capture or store any webcam images.

**Comment by Kalovelo** [comment]
Hello! Could i work on this issue? Thanks!

**Comment by sbimochan** [comment]
> Hello! Could i work on this issue? Thanks!

Work it as if it's yours 😄

**Comment by Kalovelo** [comment]
> Work it as if it's yours

I see that a PR regarding this issue has been merged. Should I stop working on this since it has been solved?
